name: GenMM-GNN
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19.2
  - pandas=1.1.3
  - scikit-learn=0.23.2
  - matplotlib=3.3.2
  - tqdm=4.62.3
  - pytorch=1.10.0
  - torchvision=0.11.1
  - torchaudio=0.10.0
  - cudatoolkit=11.1